### ISSUE TITLE
Set up a CI/CD pipeline for automated deployment

### ISSUE THREAD

**Issue by 11acc** [solsylph/Debate-Chatbot#10]
From Miguel's feedback:
"The team is not doing code reviews, with PRs merged by the same person who submits the code. There are no MLOps or tests"

From issue #5
"Create a MLOps pipeline like in https://github.com/miguelgfierro/project_template/actions"

We need to set up a pipeline with PRs and merges with the appropriate roles and security involved.

**Comment by solsylph** [comment]
implemented
