### ISSUE TITLE
Make frontend skeleton online

### ISSUE THREAD

**Issue by 11acc** [solsylph/Debate-Chatbot#8]
Lorenzo please upload the frontend code you made onto a domain or webapp so that anyone can access it instead of having to boot up a localhost

I can help with this

**Comment by clorenzol** [comment]
I created a new branch and added the frontend folder. 
The code is created with react, to run it, run the following commands:
'cd frontend'
'npm start'

<img width="1440" alt="Captura de pantalla 2024-03-30 a las 11 03 23" src="https://github.com/solsylph/Debate-Chatbot/assets/118300849/bc45e819-a524-46a5-9f1e-3d38ec0a4920">

<img width="1440" alt="image" src="https://github.com/solsylph/Debate-Chatbot/assets/118300849/6829eb00-2d2f-47f0-aa6a-b29e4ffb08f6">
