### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by 11acc** [solsylph/Debate-Chatbot#9]
From Miguel's feedback:
"There are no notebooks explaining what the team is doing, no README, there is no explanation of what the team did or why they chose the technologies they chose."

Goals for this issue:
- README explaining what we are doing
- Notebook about the technologies we are using and why

As for "technologies":
- Why are we using x, y, z models
- Are we getting data from a specific place? Why?

**Comment by solsylph** [comment]
i'll work on this and focus on documentation over the next couple of days

**Comment by solsylph** [comment]
i have updated the readme and included the required specifications in the documentation. can be found in the docs folder.
